let suggestions = [
    'Ajiaco',
    'Bandeja paisa',
    'Causa Limeña',
    'Ceviche',
    'Choripan',
    'Chuleta Valluna',
    'Cocido Madrileño',
    'Enchiladas',
    'Gazpacho',
    'Lomo saltado',
    'Milanesa',
    'Paella',
    'Polenta',
    'Pozole',
    'Tacos',
];